### ISSUE TITLE
Cannot Build Solution - OutOfMemoryException

### ISSUE THREAD

**Issue by nwoodcl** [scottdurow/NetworkViewPCF#5]
Hello

Tried running the build-solution.bat file
Get most of the way through the build but it fails on building the solution files. see log output below.
There is plenty of available memory on the machine at the time, seems like a red herring error?
Thanks for any help

2020-07-01 12:35:32.595 - Info	Processing Component: Entities
2020-07-01 12:35:32.598 - Info	Processing Component: Roles
2020-07-01 12:35:32.601 - Info	Processing Component: Workflows
2020-07-01 12:35:32.602 - Info	Processing Component: FieldSecurityProfiles
2020-07-01 12:35:32.602 - Info	Processing Component: Templates
2020-07-01 12:35:32.603 - Info	Processing Component: EntityMaps
2020-07-01 12:35:32.603 - Info	Processing Component: EntityRelationships
2020-07-01 12:35:32.616 - Info	Processing Component: OrganizationSettings
2020-07-01 12:35:32.616 - Info	Processing Component: optionsets
2020-07-01 12:35:32.617 - Info	Processing Component: CustomControls
2020-07-01 12:35:33.177 - Info	 - dev1.NetworkView
2020-07-01 12:35:33.744 - Info	Processing Component: SolutionPluginAssemblies
2020-07-01 12:35:33.745 - Info	Processing Component: EntityDataProviders
2020-07-01 12:41:12.852 - Error	Exception of type 'System.OutOfMemoryException' was thrown.
2020-07-01 12:41:12.852 - Error	See log file 'bin\Release\SolutionPackager.log' for details.
2020-07-01 12:41:12.857 - Error	System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Microsoft.Crm.Tools.SolutionPackager.ZipWriter.AddFile(ZipPackage package, Uri uri, Byte[] data)
   at Microsoft.Crm.Tools.SolutionPackager.ZipWriter.WriteComponents()
   at Microsoft.Crm.Tools.SolutionPackager.SolutionPackager.Run(IPackageReader reader, IPackageWriter writer)
   at Microsoft.Crm.Tools.SolutionPackager.SolutionPackager.Run()
   at Microsoft.Crm.Tools.SolutionPackager.Program.Main(String[] args)

**Comment by acehaddock** [comment]
I was able to get it to build but it failed a lot

Would you like me to send you a solution file for managed ? 

Sent from my iPhone
Cole Haddock

**Comment by Ian-O** [comment]
I've just tried to build it, i got the following errors.
I'd really appreciate a solution file, if that is ok

.nuget\packages\microsoft.powerapps.msbuild.pcf\1.3.3\build\Microsoft.PowerApps.MSBuild.Pcf.targets(61,5): error MSB3073: The command "npm run build -- --noColor --buildMode production -
-outDir "xxxxxxxxxxxxx)\Customisations\NetworkViewPCF\NetworkViewPCF\NetworkViewPCF\out\controls" --buildSource MSBuild" exited with code 9009.
xxxxxxxx\Customisations\NetworkViewPCF\NetworkViewPCF\NetworkViewPCF\NetworkViewPCF.pcfproj]

**Comment by scottdurow** [comment]
Here is a pre-built version - https://github.com/scottdurow/NetworkViewPCF/releases/tag/1.0.0.7
